{
    "acRate": 71.60888785481619,
    "difficulty": "Medium",
    "freqBar": null,
    "frontendQuestionId": "2721",
    "isFavor": false,
    "paidOnly": false,
    "status": null,
    "title": "Execute Asynchronous Functions in Parallel",
    "titleSlug": "execute-asynchronous-functions-in-parallel",
    "topicTags": [],
    "hasSolution": true,
    "hasVideoSolution": false,
    "codeSnippets": [
        {
            "lang": "JavaScript",
            "langSlug": "javascript",
            "code": "/**  * @param {Array<Function>} functions  * @return {Promise<any>}  */ var promiseAll = function(functions) {      };  /**  * const promise = promiseAll([() => new Promise(res => res(42))])  * promise.then(console.log); // [42]  */"
        },
        {
            "lang": "TypeScript",
            "langSlug": "typescript",
            "code": "type Fn<T> = () => Promise<T>  function promiseAll<T>(functions: Fn<T>[]): Promise<T[]> {      };  /**  * const promise = promiseAll([() => new Promise(res => res(42))])  * promise.then(console.log); // [42]  */"
        }
    ],
    "content": "Given an array ofasynchronous functionsfunctions, return a new promise promise. Each function in the array accepts no argumentsand returns a promise. All the promises should be executed in parallel. promise resolves:  When all the promises returned fromfunctionswere resolved successfully in parallel.The resolvedvalue ofpromise should be an array of all the resolved values of promises in the same order as they were in thefunctions. The promise should resolve when all the asynchronous functions in the array have completed execution in parallel.  promise rejects:  When anyof the promisesreturned fromfunctionswere rejected.promise should alsorejectwith the reason of the first rejection.  Please solve it without using the built-inPromise.allfunction.  Example 1:  Input: functions = [  () => new Promise(resolve => setTimeout(() => resolve(5), 200)) ] Output: {\"t\": 200, \"resolved\": [5]} Explanation:  promiseAll(functions).then(console.log); // [5]  The single function was resolved at 200ms with a value of 5.  Example 2:  Input: functions = [     () => new Promise(resolve => setTimeout(() => resolve(1), 200)),      () => new Promise((resolve, reject) => setTimeout(() => reject(\"Error\"), 100)) ] Output: {\"t\": 100, \"rejected\": \"Error\"} Explanation: Since one of the promises rejected, the returned promise also rejected with the same error at the same time.  Example 3:  Input: functions = [     () => new Promise(resolve => setTimeout(() => resolve(4), 50)),      () => new Promise(resolve => setTimeout(() => resolve(10), 150)),      () => new Promise(resolve => setTimeout(() => resolve(16), 100)) ] Output: {\"t\": 150, \"resolved\": [4, 10, 16]} Explanation: All the promises resolved with a value. The returned promise resolved when the last promise resolved.   Constraints:  functionsis an array of functions that returns promises 1 <= functions.length <= 10  "
}